repos:
- repo: local
  hooks:
    - id: clang-format
      name: Formatting C/C++ code with clang-format.
      language: system
      files: \.(.c|cc|cpp|h)$
      entry: clang-format -i
      args: [--style=file]
